"""Auto migration

Revision ID: 29f8e3a24fa9
Revises: 
Create Date: 2025-12-03 14:02:46.792273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f8e3a24fa9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('chat_messages', 'timestamp')
    op.alter_column('chat_sessions', 'session_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_sessions', 'session_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('chat_messages', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.drop_column('chat_messages', 'created_at')
    # ### end Alembic commands ###
